server:
  port: 8080

spring:
  ai:
    zhipuai:
      base-url: https://open.bigmodel.cn/api/paas
      # 启动命令行中传递环境变量，IDEA执行貌似识别不了系统中的环境变量
      api-key: ${ZHIPUAI_API_KEY}
      chat:
        # Chat 选项可以在客户端调用时手动修改
        options:
          model: GLM-4-0520

logging:
  level:
    root: info
  config: classpath:logback-spring.xml